Fix configuration paths and restore HID/STORAGE logic in ATTACKMODE

diff --git a/bin/ATTACKMODE b/bin/ATTACKMODE
--- a/bin/ATTACKMODE
+++ b/bin/ATTACKMODE
@@ -124,7 +124,41 @@ mkdir $DEV_DIR
 cd $DEV_DIR
 
 #Setup USB Stuff
-# ... (rest of descriptors) ...
+echo $ID_VENDOR > idVendor # Linux Foundation
+echo $ID_PRODUCT > idProduct # Multifunction Composite Gadget
+echo $BDC_DEVICE > bcdDevice # v1.0.0
+echo $BDC_USB > bcdUSB # USB2
+
+mkdir -p strings/0x409
+echo $SERIAL_NUMBER > strings/0x409/serialnumber
+echo $MANUFACTURER > strings/0x409/manufacturer 
+echo $PRODUCT > strings/0x409/product 
+
+N="usb0"
+C=1
+
+if [ "$AM_SERIAL" == "yes" ]
+then
+    mkdir -p functions/acm.$N
+fi
+
+mkdir -p configs/c.$C/strings/0x409
+
+#STORAGE
+if [ "$AM_STORAGE" == "yes" ]
+then
+	mkdir -p ${FLASHDRIVE_FILE/img/d}
+	if ! mountpoint -q ${FLASHDRIVE_FILE/img/d}; then
+		mount -o loop,ro -t vfat $FLASHDRIVE_FILE ${FLASHDRIVE_FILE/img/d}
+	fi
+	mkdir -p functions/mass_storage.$N
+	echo 1 > functions/mass_storage.$N/stall
+	echo 0 > functions/mass_storage.$N/lun.0/cdrom
+	echo 0 > functions/mass_storage.$N/lun.0/ro
+	echo 0 > functions/mass_storage.$N/lun.0/nofua
+	echo $FLASHDRIVE_FILE > functions/mass_storage.$N/lun.0/file
+	ln -s functions/mass_storage.$N configs/c.$C/
+fi
 
 # Probing for correct HID function name
 HID_FUNC=""
@@ -134,7 +168,6 @@ if [ "$AM_HID" == "yes" ]; then
         if mkdir functions/$f.0 2>/dev/null; then
             HID_FUNC=$f
             echo "  - Found working HID function type: $HID_FUNC"
-            # We already created it, so let's use it.
             break
         fi
     done
@@ -142,17 +175,26 @@ fi
 
 if [ "$AM_HID" == "yes" ] && [ -n "$HID_FUNC" ]
 then
-    # Directory already exists from probe
     echo 1 > functions/$HID_FUNC.0/protocol
     echo 1 > functions/$HID_FUNC.0/subclass
     echo 8 > functions/$HID_FUNC.0/report_length
     echo -ne \\x05\\x01\\x09\\x06\\xa1\\x01\\x05\\x07\\x19\\xe0\\x29\\xe7\\x15\\x00\\x25\\x01\\x75\\x01\\x95\\x08\\x81\\x02\\x95\\x01\\x75\\x08\\x81\\x03\\x95\\x05\\x75\\x01\\x05\\x08\\x19\\x01\\x29\\x05\\x91\\x02\\x95\\x01\\x75\\x03\\x91\\x03\\x95\\x06\\x75\\x08\\x15\\x00\\x25\\x65\\x05\\x07\\x19\\x00\\x29\\x65\\x81\\x00\\xc0 > functions/$HID_FUNC.0/report_desc
     ln -s functions/$HID_FUNC.0 configs/c.$C/
 elif [ "$AM_HID" == "yes" ]; then
-    echo "  ! Error: Could not create HID function. Module may be loaded but type not registered."
-    echo "    Try: dmesg | grep usb"
+    echo "  ! Error: Could not create HID function."
 fi
 
+#ETHERNET
+if [ "$AM_ETHERNET" == "yes" ]
+then	
+    mkdir -p functions/ecm.$N
+    HOST="48:6f:73:74:50:43" # "HostPC"
+    SELF="42:61:64:55:53:42" # "BadUSB"
+    echo $HOST > functions/ecm.$N/host_addr
+    echo $SELF > functions/ecm.$N/dev_addr
+    echo "Config $C: ECM network" > configs/c.$C/strings/0x409/configuration 
+    ln -s functions/ecm.$N configs/c.$C/
+fi
 
 echo 250 > configs/c.$C/MaxPower 
 if [ "$AM_SERIAL" == "yes" ]
